<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js(array(
    pi::url('static/js/html5shiv.js') => array(
        'conditional' => 'lt IE 9'
    ),
    pi::url('static/js/respond.min.js') => array(
        'conditional' => 'lt IE 9'
    ),
));

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css'
));

// Load front.css
$this->css(array(
    $this->assetTheme('css/front.css'),
    $this->assetTheme('css/animate.min.css'),
));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Apple icons
// Apple icon for iphone
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'href'  => $this->assetTheme('image/touch-icon-iphone.png')
));
// Apple icon for ipad
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png')
));
// Apple icon for iphone retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png')
));
// Apple icon for ipad retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png')
));

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'href'  => $this->favicon(),
));

// Load google analytics code
$this->ga();

// Get module name
$module = Pi::service('module')->current();

// Get blocks
$blocks = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(array('prefix' => array(array('label' => __('Home'), 'href' => $this->url('home')))));
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?>">
<!-- Header: brand, slogan, user bar -->
<header class="pi-header">
    <div class="container">
        <div class="row clearfix">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="navbar navbar-default yamm">
                        <div class="navbar-header">
                            <button class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-grid">
                                <i class="fa fa-bars"></i>
                            </button>
                            <div class="pi-header-logo navbar-brand">
                                <ul class="list-inline">
                                    <li>
                                        <a href="<?php echo $this->url('home'); ?>" title="<?php echo _escape($sitename); ?>">
                                            <img src="<?php echo $this->logo(); ?>" alt="<?php echo _escape($sitename); ?>">
                                        </a>
                                    </li>
                                    <li>
                                        <?php if ($module == 'system') { ?>
                                            <h1>
                                                <a href="<?php echo $this->url('home'); ?>" title="<?php echo _escape($sitename); ?>">
                                                    <?php echo _escape($sitename); ?>
                                                </a>
                                            </h1>
                                        <?php } else { ?>
                                            <h2>
                                                <a href="<?php echo $this->url('home'); ?>" title="<?php echo _escape($sitename); ?>">
                                                    <?php echo _escape($sitename); ?>
                                                </a>
                                            </h2>
                                        <?php } ?>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div id="navbar-collapse-grid" class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li><a href="https://www.cafeyab.com/guide/manage" title="ثبت و مدیریت کافه">ثبت و مدیریت کافه</a></li>
                                <li><a href="https://www.cafeyab.com/guide" title="فهرست کافه ها">فهرست کافه ها</a></li>
                                <li><a href="https://www.cafeyab.com/shop" title="فروشگاه">فروشگاه</a></li>
                                <!-- <li class="dropdown yamm-fw">
                                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">جسنجوی کافه ها<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li class="grid-menu">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <?php // echo $this->widget('guide-search'); ?>
                                                </div>
                                                <div class="col-sm-12">
                                                    <?php // echo $this->widget('guide-map'); ?>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </li>
                                <li class="dropdown yamm-fw">
                                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">فروشگاه<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li class="grid-menu">
                                            <div class="row">
                                                <div class="col-sm-3">
                                                    <h5>منوی فروشگاه منوی فروشگاه</h5>
                                                    <ul class="list-unstyled">
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                    </ul>
                                                </div>
                                                <div class="col-sm-3">
                                                    <h5>منوی فروشگاه منوی فروشگاه</h5>
                                                    <ul class="list-unstyled">
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                    </ul>
                                                </div>
                                                <div class="col-sm-3">
                                                    <h5>منوی فروشگاه منوی فروشگاه</h5>
                                                    <ul class="list-unstyled">
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                    </ul>
                                                </div>
                                                <div class="col-sm-3">
                                                    <h5>منوی فروشگاه منوی فروشگاه</h5>
                                                    <ul class="list-unstyled">
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                        <li><a href="#" title="منوی فروشگاه منوی فروشگاه">منوی فروشگاه منوی فروشگاه</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </li>
                                <li class="dropdown yamm-fw">
                                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">منطقه باریستا<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li class="grid-menu">
                                            <div class="row">
                                                <div class="col-sm-3">
                                                    <h5>منوی مطالب منوی مطالب</h5>
                                                    <ul class="list-unstyled">
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                    </ul>
                                                </div>
                                                <div class="col-sm-3">
                                                    <h5>منوی مطالب منوی مطالب</h5>
                                                    <ul class="list-unstyled">
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                    </ul>
                                                </div>
                                                <div class="col-sm-3">
                                                    <h5>منوی مطالب منوی مطالب</h5>
                                                    <ul class="list-unstyled">
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                    </ul>
                                                </div>
                                                <div class="col-sm-3">
                                                    <h5>منوی مطالب منوی مطالب</h5>
                                                    <ul class="list-unstyled">
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                        <li><a href="#" title="منوی مطالب منوی مطالب">منوی مطالب منوی مطالب</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </li> -->
                            </ul>
                            <?php echo $this->widget('system-user-bar'); ?>
                            <!-- <ul class="nav navbar-nav cafe-richard">
                                <li><a href="#" title="Cafés Richard">Cafés Richard</a></li>
                            </ul> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Page main content: breadcrumb, flash-messenger, blocks and module content -->
<section class="pi-main-container">
    <div class="container">
        <?php if ($breadcrumbs) { echo $breadcrumbs; } ?>
        <!-- Flash messenger -->
        <?php include $this->template('flash-messenger'); ?>
        <div class="row">
            <!-- Left zone -->
            <?php if (!empty($blocks['1'])) { ?>
                <div class="pi-zone-1 col-md-3">
                    <?php foreach ($blocks['1'] as $block) {
                        include $blockTemplate;
                    } ?>
                </div>
            <?php } ?>
            <div class="<?php
            if (isset($blocks['1']) && isset($blocks['8'])) {
                echo 'col-md-3';
            } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                echo 'col-md-9';
            } else {
                echo 'col-md-12';
            }
            ?>">
                <!-- Center top zone -->
                <?php if (isset($blocks['2'])) { ?>
                    <div class="pi-zone-2">
                        <?php foreach ($blocks['2'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                    <div class="row">
                        <div class="col-md-6 pi-zone-3">
                            <?php
                            if (isset($blocks['3'])) {
                                foreach ($blocks['3'] as $block) {
                                    include $blockTemplate;
                                }
                            }
                            ?>
                        </div>
                        <div class="col-md-6 pi-zone-4">
                            <?php
                            if (isset($blocks['4'])) {
                                foreach ($blocks['4'] as $block) {
                                    include $blockTemplate;
                                }
                            }
                            ?>
                        </div>
                    </div>
                <?php } ?>
                <!-- Module content starts -->
                <?php if (!empty($content)) { ?>
                    <div class="<?php echo $module; ?>">
                        <div class="pi-module-content" ng-app="<?php echo $module; ?>">
                            <?php echo $content; ?>
                        </div>
                        <?php echo Pi::service('comment')->load(array('options' => array('type' => 'js'))); ?>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
    <?php if (!empty($blocks['0'])) { ?>
        <div class="pi-zone-0">
            <?php foreach ($blocks['0'] as $block) {
                include $blockTemplate;
            } ?>
        </div>
    <?php } ?>
    <div class="container">
        <div class="row">
            <div class="<?php
            if (isset($blocks['1']) && isset($blocks['8'])) {
                echo 'col-md-3';
            } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                echo 'col-md-9';
            } else {
                echo 'col-md-12';
            }
            ?>">
                <!-- Module content ends -->
                <?php if (isset($blocks['5']) || isset($blocks['6'])) { ?>
                    <div class="row">
                        <div class="col-md-6 pi-zone-5">
                            <?php
                            if (isset($blocks['5'])) {
                                foreach ($blocks['5'] as $block) {
                                    include $blockTemplate;
                                }
                            }
                            ?>
                        </div>
                        <div class="col-md-6 pi-zone-6">
                            <?php
                            if (isset($blocks['6'])) {
                                foreach ($blocks['6'] as $block) {
                                    include $blockTemplate;
                                }
                            }
                            ?>
                        </div>
                    </div>
                <?php } ?>
                <!-- Center bottom zone -->
                <?php if (isset($blocks['7'])) { ?>
                    <div class="pi-zone-7">
                        <?php foreach ($blocks['7'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
            </div>
            <!-- Right zone -->
            <?php if (isset($blocks['8'])) { ?>
                <div class="col-md-3 pi-zone-8">
                    <?php foreach ($blocks['8'] as $block) {
                        include $blockTemplate;
                    } ?>
                </div>
            <?php } ?>
        </div>
        <!-- Bottom foot zone -->
        <?php if (isset($blocks['99'])) { ?>
            <div class="pi-zone-99">
                <?php foreach ($blocks['99'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
        <?php } ?>
    </div>
</section>
<footer class="pi-footer">
    <div class="container">
        <div class="row clearfix">
            <div class="col-md-7 col-sm-12 col-xs-12 text-justify">
                <h4>درباره کافه یاب</h4>
                <p>کافه‌یاب به عنوان مرجع معرفی و اطلاع‌رسانی کافه‌های ایران، در تابستان ۹۳ فعالیت خود را آغاز نمود. این وب‌سایت در نظر دارد تا با معرفی کافه‌ها، کافی‌شاپ‌ها، شیرینی فروشی‌ها و قهوه فروشی‌ها، امکان آشنایی کاربران را با این مکان‌ها و خدماتشان، فراهم کند. همچنین امکان درج و به روز رسانی اطلاعات کافه‌ها توسط صاحبان آن‌ها در وب‌سایت وجود دارد.</p>
                <p>تمامی کالاها و خدمات این وب‌سایت، حسب مورد دارای مجوزهای لازم از مراجع مربوطه می‌باشند و فعالیت‌های این وب‌سایت تابع قوانین و مقررات جمهوری اسلامی ایران است.</p>
            </div>
            <div class="col-md-5 col-sm-12 col-xs-12">
                <div class="pi-footer-menu">
                    <div class="col-md-6 col-sm-6 col-xs-6">
                        <ul class="list-unstyled">
                            <li><a title="درباره ما" href="https://www.cafeyab.com/page/about-us"><i class="fa fa-angle-left"></i> درباره ما</a></li>
                            <li><a title="تماس با ما" href="https://www.cafeyab.com/contact"><i class="fa fa-angle-left"></i> تماس با ما</a></li>
                            <li><a title="راهنمای ثبت کافه" href="https://www.cafeyab.com/page/registration-guide"><i class="fa fa-angle-left"></i> راهنمای ثبت کافه</a></li>
                            <li><a title="راهنمای کاربران" href="https://www.cafeyab.com/page/user-guide/"><i class="fa fa-angle-left"></i> راهنمای کاربران</a></li>
                            <li><a title="قوانین و مقررات" href="https://www.cafeyab.com/page/rules"><i class="fa fa-angle-left"></i> قوانین و مقررات</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-6">
                        <ul class="list-unstyled">
                            <li><a title="اخبار" href="https://www.cafeyab.com/news/topic/news"><i class="fa fa-angle-left"></i> اخبار</a></li>
                            <li><a title="یاداشت" href="https://www.cafeyab.com/news/topic/note"><i class="fa fa-angle-left"></i> یاداشت</a></li>
                            <li><a title="آموزش" href="https://www.cafeyab.com/news/topic/instruction"><i class="fa fa-angle-left"></i> آموزش</a></li>
                            <li><a title="فروشگاه" href="https://www.cafeyab.com/shop"><i class="fa fa-angle-left"></i> فروشگاه</a></li>
                        </ul>
                    </div>
                    <div class="pi-social col-md-12 col-sm-12 col-xs-12">
                        <ul class="list-inline text-right">
                            <li class="pi-social-twitter"><a title="تویتر" href="https://twitter.com/cafeyab" target="_blank"><i class="fa fa-twitter"></i></a></li>
                            <li class="pi-social-facebook"><a title="فیسبوک" href="https://www.facebook.com/cafeyaab" target="_blank"><i class="fa fa-facebook"></i></a></li>
                            <li class="pi-social-pinterest"><a title="پین‌ترست" href="https://www.pinterest.com/cafeyab" target="_blank"><i class="fa fa-pinterest"></i></a></li>
                            <li class="pi-social-google"><a title="گوگل پلاس" href="https://plus.google.com/+CafeYab" target="_blank" rel="publisher"><i class="fa fa-google-plus"></i></a></li>
                            <li class="pi-social-instagram"><a title="اینستاگرام" href="https://www.instagram.com/cafe.yab" target="_blank"><i class="fa fa-instagram"></i></a></li>
                            <li class="pi-social-foursquare"><a title="Foursquare" href="https://www.foursquare.com/cafeyab" target="_blank"><i class="fa fa-foursquare"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-6">
                <div rel="license">
                    تمام حقوق مطالب برای وب سایت <a title="کافه یاب" href="https://www.cafeyab.com">کافه یاب</a> محفوظ است.
                </div>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="text-right" rel="license">
                    طراحی و توسعه <a title="فراگسترش" href="http://www.faragostaresh.com" target="_blank">فراگسترش</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<?php $this->footScript()->appendFile($this->assetTheme('js/front.js')); ?>
</body>
</html>