<div class="user-bar">
    <ul class="nav navbar-nav navbar-right">
        <?php if (!$block['user']['uid']) { ?>
            <li>
                <a title="<?php echo _b('Login'); ?>" href="<?php echo $block['user']['login']; ?>">
                    <i class="fa fa-sign-in"></i>
                    <?php echo _b('Login'); ?>
                </a>
            </li>
            <li>
                <a title="<?php echo _b('Register'); ?>" href="<?php echo $block['user']['register']; ?>">
                    <i class="fa fa-arrow-circle-down"></i>
                    <?php echo _b('Register'); ?>
                </a>
            </li>
        <?php } else { ?>
            <li class="dropdown">
                <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
                    <?php echo $block['user']['avatar']; ?>
                    <?php echo _escape($block['user']['name']); ?>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                    <li><a title="فهرست علاقه مندی ها" href="https://www.cafeyab.com/guide/favourite">فهرست علاقه مندی ها</a></li>
                    <li><a title="تنظیمات حساب کاربری" href="https://www.cafeyab.com/user/account/">تنظیمات حساب کاربری</a></li>
                    <li><a title="تغییر کلمه عبور" href="https://www.cafeyab.com/user/password/">تغییر کلمه عبور</a></li>
                    <li><a title="تغییر آواتار" href="https://www.cafeyab.com/user/avatar/">تغییر آواتار</a></li>
                    <li><a title="به روز کردن پروفایل پایه" href="https://www.cafeyab.com/user/profile/edit.profile/group/1">به روز کردن پروفایل پایه</a></li>
                </ul>
            </li>
            <li>
                <a title="<?php echo _b('Logout'); ?>" href="<?php echo Pi::url($block['user']['logout']); ?>">
                    <i class="fa fa-power-off"></i>
                    <?php echo _b('Logout'); ?>
                </a>
            </li>
        <?php } ?>
    </ul>
</div>